### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by rongnb666** [SeongJinAhn/VGNAE#6]
作者你好，我是来自中国的大二学生，最近在研究有关二分网链路预测的模型，有幸在github上看到您的代码，我们现在想复现下您的模型，但是我们没有相关的数据，我们打算通过这个模型研究金融领域的预测，请问您有这方面的数据集吗？如果你有相关的数据集分享，我将非常的感谢。我的邮箱是1103456953@qq.com.
作者你好，我是来自中国的大二学生，最近在研究有关二分网链路预测的模型，有幸在github上看到您的代码，我们现在想复现下您的模型，但是我们没有相关的数据，我们打算通过这个模型研究金融领域的预测，请问您有这方面的数据集吗？如果你有相关的数据集分享，我将非常的感谢。我的邮箱是1103456953@qq.com.
Hello, the author. I'm a sophomore from China. Recently, I was studying the prediction model of the binary network link. I was lucky to see your code on github. We want to reproduce your model now, but we don't have relevant data. We plan to study the prediction in the financial field through this model. Do you have a dataset in this area? If you have relevant data sets to share, I will be very grateful. My email is 1103456953@qq.com.

**Comment by SeongJinAhn** [comment]
Hi rongnb666!!
I wish I can help you but i don't know good structured data in the financial field....
